config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :posts, only: %i[index show new create]
  resources :sessions, only: %i[new create destroy]
  root to: 'posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  belongs_to :user
  has_one_attached :image

  validates :title, presence: true

  def standard_image
    height = image.metadata[:height].to_i
    width = image.metadata[:width].to_i
    size = height > width ? width : height
    image.variant(gravity: 'center', extent: "#{size}x#{size}", resize_to_limit: [400, 400])
  end

  def big_image
    height = image.metadata[:height].to_i
    width = image.metadata[:width].to_i
    size = height > width ? width : height
    image.variant(gravity: 'center', extent: "#{size}x#{size}", resize_to_limit: [1000, 1000])
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :posts, dependent: :destroy

  validates :first_name, :last_name, :password, presence: true
  validates :email,
            presence: true,
            uniqueness: true,
            format: { with: URI::MailTo::EMAIL_REGEXP }

  has_secure_password
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include Pagy::Backend

  helper_method :current_user

  def current_user
    return unless cookies.encrypted[:user_id]

    @current_user ||= User.find(cookies.encrypted[:user_id])
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :set_post, only: %i[show]

  def index
    @pagy, @posts = pagy(Post.all.order(created_at: :desc), items: 3)
    respond_to do |format|
      format.html
      format.js
    end
  end

  def new
    @post = Post.new
  end

  def show; end

  def create
    @post = Post.new(post_params)
    return redirect_to root_path if @post.save

    render :new
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params
      .require(:post)
      .permit(:title, :image)
      .merge(user: current_user)
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.find_by(email: session_params[:email])
    if @user&.authenticate(session_params[:password])
      cookies.encrypted[:user_id] = @user.id
      redirect_to root_path
    else
      @user = User.new(email: session_params[:email])
      render :new
    end
  end

  def destroy
    cookies.delete :user_id

    redirect_to root_path
  end

  private

  def session_params
    params.require(:user).permit(:email, :password)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def linear_gradient(colors, direction = '')
    direction = direction.present? ? "#{direction}," : ''
    "linear-gradient(#{direction}#{colors.join(',')})"
  end

  def lazy_image_tag(source, options = {})
    options[:data] = {} unless options[:data]
    options[:data][:lazy_image] = url_for(source)
    image_tag('', options)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instagramo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="header-frame">
      <section class="section-container">
        <h1 class="header-title">Instagramo for <%= current_user&.first_name %></h1>
        <% if current_user %>
          <%= link_to 'Sign out', session_path(current_user), method: :delete %>
        <% else %>
          <%= link_to 'Sign in', new_session_path %>
        <% end %>
      </section class="section-container">
    </header>
    <%= yield %>
  </body>
</html>

app/views/posts/_post.html.erb
<% cache post do %>
  <% image = post.image.attached? ? post.standard_image : '' %>
  <% image_colors = post.image.metadata[:colors] || [] %>

  <article class="post-frame">
    <%= lazy_image_tag(image, style: "background: #{linear_gradient(image_colors)}", class: 'post-image') %>
    <h3 class="post-username"><%= post.user.email %></h3>
    <h3 class="post-title"><%= post.title %></h3>
  </article>
<% end %>

app/views/posts/index.html.erb
<section class="section-container" id="post-container">
  <%= link_to 'New Post', new_post_path %>
  <%= render @posts %>
  <%= tag.div data: { lazy_request: posts_path(page: @pagy.next, format: :js) } if @pagy.next %>
</section>

app/views/posts/index.js.erb
(() => {
  const CONTAINER_SELECTOR = '#post-container'
  const container = document.querySelector(CONTAINER_SELECTOR)

  if (!container) { return; }

  container.insertAdjacentHTML('beforeend', "<%= escape_javascript(render @posts).html_safe %>")

  <% if @pagy.next %>
    container.insertAdjacentHTML('beforeend', "<%= escape_javascript(tag.div data: { lazy_request: posts_path(page: @pagy.next, format: :js) }).html_safe %>")
  <% end %>
})()

app/views/posts/new.html.erb
<%= form_with(model: @post, local: true) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :image %>
  <%= f.file_field :image, accept:'image/*' %>
  <%= f.submit %>
<% end %>

app/views/posts/show.html.erb
<section>
  <%= link_to 'Home', root_path %>
  <article>
    <%= image_tag @post.big_image if @post.image.attached? %>
    <h3><%= @post.title %></h3>
  </article>
</section>